[package]
name = "day02"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
miette = { version = "3.3.0", features = ["fancy"] }
clap = "3.0.10"
thiserror = "1.0.34"
nom = "7.1.0"
