[package]
name = "day02"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
miette = { version = "5.1.1", features = ["fancy"] }
clap = "3.0.10"
thiserror = "1.0.30"
nom = "7.1.0"
